telegram:
  bot:
    token: "7399299200:AAHtZJQp0mh-j3YJ-u6yRfn1X5QiUyMdgu8"
    username: "TheNaIIsBot"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/the_nails
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect


logging:
  config: "classpath:logback.xml"